config/routes.rb
Rails.application.routes.draw do
  get 'news/index'

	devise_for :users

	root to: "static_pages#home"

	get "/alt" => 'static_pages#alt'

	resources :users  
	resources :artworks do 
		resource :like, module: :artworks
	end
	resources :venues
	resources :conversations do
		resources :messages

		collection do 
			get :inbox
			get :all, action: :index
			get :sent 
			get :trash 
		end
	end
	resources :friendships

	# match 'auth/:provider/callback', to: 'sessions#create'
	
	get "artworks" => 'artworks#index'
	get "venues" => 'venues#index'

	get "my_friends", to: 'users#my_friends'
	get 'search_friends', to: "users#search"
	post 'add_friend', to: "users#add_friend" 

	get "thanks", to: "users#thanks"
	get "stripe", to: "users#stripe"

	get "news", to: 'news#index'

end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :user
	has_many :users, through: :messages

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	def index 
		@conversations = current_user.mailbox.conversations
	end

	def inbox 
		@conversations = current_user.mailbox.inbox
		render action: :index
	end 

	def sent 
		@conversations = current_user.mailbox.sentbox
		render action: :index
	end 

	def trash 
		@conversations = current_user.mailbox.trash
		render action: :index
	end 

	def show
		@conversation = current_user.mailbox.conversations.find(params[:id])
		@conversation.mark_as_read(current_user)
	end

	def new 
		@recipients = User.all - [@current_user]
	end

	def create 
		@recipients = User.where(params[:user_id])
		receipt = current_user.send_message(@recipients,
			params[:body],
			params[:subject], 
			true, 
			params[:attachment],
			)
		# @conversation = Conversation.new
		# (@conversation.users.uniq - [current_user]).each do |user|
        	# Notification.create(recipient: user, actor: current_user, action: "posted", notifiable: @message)
      	# end
		redirect_to all_conversations_path
	end


  # def create
  #   recipients = User.where(id: conversation_params[:recipients])
  #   receipt = current_user.send_message(recipients, 
  #   	conversation_params[:body], 
  #   	conversation_params[:subject]
  #   	).conversation
  #   flash[:success] = "Your message was successfully sent!"
  #   redirect_to conversation_path(conversation)
  # end

  # private

  # def conversation_params
  #   params.require(:conversation).permit(:subject, :body,recipients:[])
  # end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<%= link_to "Send new message", new_conversation_path %>

<hr />
	Inbox (<%= current_user.mailbox.inbox.unread(current_user).count %>) | 
	All Conversations (<%= current_user.mailbox.conversations.count %>) |
	Sent (<%= current_user.mailbox.sentbox.count %>) |
	Trash (<%= current_user.mailbox.trash.count %>)
<hr />

Total Conversations: <%= @conversations.count %>

<br />
<br />

<% @conversations.each do |conversation| %>
	<div>
		<% if conversation.is_unread?(current_user) %>
		<strong>
			<%= link_to conversation.subject, conversation_path(conversation) %>, <%= conversation.created_at.strftime("%m/%d/%Y %l:%M %p ") %>
		</strong>
		<% else %>
			<%= link_to conversation.subject, conversation_path(conversation) %>, <%= conversation.created_at.strftime("%m/%d/%Y %l:%M %p ") %>
		<% end %>
	</div>
<% end %>

app/views/conversations/new.html.erb
<h1>Send new message</h1>

<%= form_tag conversations_path, method: :post, multipart: true do %>

<!-- <div id="friend-lookup">
    <%= form_tag search_friends_path, remote: true, method: :get do %>
    <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-6">
            <%= text_field_tag :search_param, params[:search_param],
            	placeholder: "First name or Last name", autofocus: true,
                class: 'form-control search-box input-lg'  %>
        </div>    

        <div class="col-md-2">
            <%= button_tag(type: :submit, class: "btn btn-warning btn-lg purple-button") do %>
                <i></i> Search
            <% end %>
        </div>
    </div>

    <% end %>
</div> -->


	<div class="form-group row no-padding col-md-12">
	<div class="col-md-8">
	<%= select_tag :user_id, options_from_collection_for_select(User.all - [@current_user], :id, :name) %>
	</div>
	</div>

	<div class="form-group row no-padding text-center col-md-12">

	<div class="col-md-8">
		<%= text_field_tag :subject, nil, placeholder: "Subject", class: 'form-control input-lg' %>
	</div>

	<div class="col-md-8">
		<%= text_area_tag :body, nil, placeholder: "Leave a message", class: 'form-control input-lg' %>
	</div>

	</div>

	<div>
		<%= file_field_tag :attachment %>
	</div>

	<br />

	<div>
		<%= button_tag(type: :submit, class: "btn btn-warning btn-lg purple-button") do %>
	                <i></i> Send Message	
	    <% end %>
	</div>
<% end %>
<hr />

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<hr />

<% @conversation.receipts_for(current_user).each_with_index do |receipt, index| %>
	<br />
	<div>
		<div>Message # <%= index + 1 %> from <i><%= receipt.message.sender.name %>, <%= receipt.message.sender.role %></i></div>
		<br />
		<p><%= receipt.message.body %></p>
		<div>
			<% if receipt.message.attachment? %>
				<%= link_to receipt.message.attachment.file.filename, receipt.message.attachment.url, target: :blank %>
			<% else %>
				what
			<% end %>
		</div>
		<br />
		<div>
			This message was sent on: <%= receipt.message.created_at.strftime("%b. %e, %l:%M %p") %>
		</div>
	</div>
<% end %>

<hr />

<p>Your response:</p>
<%= form_tag conversation_messages_path(@conversation), { method: :post, multipart: true } do %>
	<div>
		<%= text_area_tag :body %>
		<%= file_field_tag :attachment %>
	</div>

	<%= submit_tag %>	
<% end %>
<hr />

<%= link_to "Send new message", new_conversation_path %>

<hr />