config/routes.rb
Rails.application.routes.draw do
  get 'news/index'

	devise_for :users

	root to: "static_pages#home"

	get "/alt" => 'static_pages#alt'

	resources :users  
	resources :artworks do 
		resource :like, module: :artworks
	end
	resources :venues
	resources :conversations do
		resources :messages

		collection do 
			get :inbox
			get :all, action: :index
			get :sent 
			get :trash 
		end
	end
	resources :friendships

	# match 'auth/:provider/callback', to: 'sessions#create'
	
	get "artworks" => 'artworks#index'
	get "venues" => 'venues#index'

	get "my_friends", to: 'users#my_friends'
	get 'search_friends', to: "users#search"
	post 'add_friend', to: "users#add_friend" 

	get "thanks", to: "users#thanks"
	get "stripe", to: "users#stripe"

	get "news", to: 'news#index'

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
	belongs_to :user
	has_many :likes

	validates :title, presence: true, length: { minimum: 3, maximum: 50 } 
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :price, presence: true
	validates :user_id, presence: true

	has_attached_file :image, styles: { large: "600x600#", medium: "300x300#", show: "200x200#", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    has_one :payment
    # accepts_nested_attribute_for :payment
end

app/controllers/artworks/likes_controller.rb
class Artworks::LikesController < ApplicationController 
	before_action :authenticate_user!
	before_action :set_artwork 

	def create 
		@artwork.likes.where(user_id: current_user.id).first_or_create

		respond_to do |format|
			format.html { redirect_to @artwork }
			format.js
		end
	end

	def destroy
		@artwork.likes.where(user_id: current_user.id).destroy_all

		respond_to do |format|
			format.html { redirect_to @artwork }
			format.js
		end
	end

private 

	def set_artwork 
		@artwork = Artwork.find(params[:artwork_id])
	end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
	# before_action :authenticate_user!, only: :show
	before_action :authenticate_user!, only: :edit
	before_filter :authenticate_user!, only: :new
	after_action :verify_authorized
	
	def new 
		@artwork = Artwork.new
		authorize User
	end

	def create
		@artwork = Artwork.new(artwork_params)
		@artwork.user = current_user
		authorize User
		if @artwork.save
			flash[:success] = "Artwork was successfully uploaded"
			redirect_to artwork_path(@artwork)
		else
			render 'new'
		end
	end

	def edit
		@artwork = Artwork.find(params[:id])
		authorize User
	end

	def update
		@artwork = Artwork.find(params[:id])
		authorize User
		if @artwork.update(artwork_params)
			flash[:success] = "Artwork was successfully updated"
			redirect_to artwork_path(@artwork)
		else
			render 'edit'
		end
	end

	def show 
		@artwork = Artwork.find(params[:id])
		authorize User
	end

	def payment 
        @artwork = Artwork.find(params[:id])
        @artwork.user = current_user
        authorize User
    end

	def index
		@artworks = Artwork.paginate(page: params[:page], per_page: 12)
		authorize User
	end

	def destroy
		@artwork = Artwork.find(params[:id])
		authorize User
		@artwork.destroy
		flash[:danger] = "Artwork was successfully deleted"
		redirect_to artworks_path
	end

private 
	def artwork_params
		params.require(:artwork).permit(:title, :description, :image, :price)
	end

end

app/views/artworks/_artworkform.html.erb
	<% if @artwork.errors.any? %>
		<div class="row">
		  	<div class="col-xs-8 col-xs-offset-2">
		  		<div class="panel panel-danger">
		  			<div class="panel-heading">
		  				<h3 class="panel-title">
		  					<%= pluralize(@artwork.errors.count, "error") %>
		  					prohibited this artwork from being uploaded
		  				</h3>
		  				<div class="panel-body">
		  					<ul>
		  						<% @artwork.errors.full_messages.each do |msg| %>
									<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>

	<%= form_for @artwork, html: { multipart: true } do |f| %>
		<br />
		<p class="white-text">
			<%= f.file_field :image %>
		</p>
		<br />
		<div class= "form-group padding">
	        <div class="col-sm-6">
	        	<%= f.text_field :title, class: "form-control", placeholder: "What's the title of your artwork?", autofocus: true %>
	    </div>
	        <div class="col-sm-6">
	        	<%= f.text_field :price, class: "form-control", placeholder: "Please set a price" %>
	        	<br />
	    </div>
	    </div>
	    <div class= "form-group padding">
	        <div class="col-sm-12">
	        	<%= f.text_area :description, class: "form-control", placeholder: "Lastly, enter a description", rows: 5 %>
	        	<br />
	    </div>
	    </div>
		<div class="form-group">
	            <div class="col-sm-12">
	              <%= f.submit "Upload your art!", class: 'btn green-button btn-lg' %>
	            </div>
	          </div>
	<% end %>

app/views/artworks/_form.html.erb
<% if @artwork.errors.any? %>
<h3>The following errors prevented the artwork from being uploaded:</h3>
<ul>
<% @artwork.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for @artwork, html: { multipart: true } do |f| %>
	<p>
		<%= f.label :artwork %><br/>
		<%= f.file_field :image %>
	</p>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/artworks/_likes.html.erb
<% if user_signed_in? && current_user.likes?(@artwork) %>
	<%= link_to "Unlike", artwork_like_path(@artwork), remote: true, method: :delete %>
<% else %>
	<%= link_to "Like", artwork_like_path(@artwork), remote: true, method: :post %>
<% end %>

<%= @artwork.likes.count %>

<% @artwork.likes.each do |like| %>
	<%= image_tag like.user.profile.url, width: 20, height: 20 %>
<% end %>

app/views/artworks/_payment.html.erb
<%= form_for @artwork.user, html: { multipart: true } do |f| %>

	<!-- <p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</p>
		<%= fields_for( :payment ) do |p| %>
			<div class="row col-md-12">
				<div class="form-group col-md-4 no-left-padding">
					<%= p.label :card_number, "Card Number", data: { stripe: 'label'} %>
					<%= p.text_field :card_number, class: "form-control", required: true, data: { stripe: 'number'} %>
				</div>
				<div class="form-group col-md-2">
					<%= p.label :card_cvv, "Card CVV", data: { stripe: 'label'} %>
					<%= p.text_field :card_cvv, class: "form-control", required: true, data: { stripe: 'cvv'} %>
				</div>
				<div class="form-group col-md-6">

					<div class="col-md-12">
						<%= p.label :card_expires, "Card Expires", data: { stripe: 'label'} %>
					</div>
					<div class="col-md-3">
					<%= p.select :card_expires_month, options_for_select(Payment.month_options),
						{ include_blank: 'Month' },
						"data-stripe" => "exp-month",
						class: "form-control", required: true %>
					</div>
					<div class="col-md-3">
						<%= p.select :card_expires_year, options_for_select(Payment.year_options.push),
							{ include_blank: 'Year' },
							class: "form-control",
							data: { stripe: "exp-year" }, required: true %>
					</div>
				</div>
			</div>
		<% end %> -->
	<p>
		<script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="pk_test_oUwAxHeXkKSvhsJNE2BFVQVO"
            data-amount="20000"
            data-name="KEYPORT Digital"
            data-description="2 widgets"
            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
            data-locale="auto">
        </script>
	</p>
<% end %>

app/views/artworks/edit.html.erb
<div class="container">

  <div class="row" align="center">
    <div class="bg-update-your-art col-lg-12 ">

		<h1 class="green-text">Edit the details of your artwork</h1>

		
	<% if @artwork.errors.any? %>
		<div class="row">
		  	<div class="col-xs-8 col-xs-offset-2">
		  		<div class="panel panel-danger">
		  			<div class="panel-heading">
		  				<h3 class="panel-title">
		  					<%= pluralize(@artwork.errors.count, "error") %>
		  					prohibited this artwork from being uploaded
		  				</h3>
		  				<div class="panel-body">
		  					<ul>
		  						<% @artwork.errors.full_messages.each do |msg| %>
									<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>

	<%= form_for @artwork, html: { multipart: true } do |f| %>
		<br />
		<p class="white-text">
			<%= f.file_field :image %>
		</p>
		<br />
		<div class= "form-group padding">
	        <div class="col-sm-6">
	        	<%= f.text_field :title, class: "form-control", placeholder: "What's the title of your artwork?", autofocus: true %>
	    </div>
	        <div class="col-sm-6">
	        	<%= f.text_field :price, class: "form-control", placeholder: "Please set a price" %>
	        	<br />
	    </div>
	    </div>
	    <div class= "form-group padding">
	        <div class="col-sm-12">
	        	<%= f.text_area :description, class: "form-control", placeholder: "Lastly, enter a description", rows: 5 %>
	        	<br />
	    </div>
	    </div>
		<div class="form-group">
	            <div class="col-sm-12">
	              <%= f.submit "Update your artwork!", class: 'btn green-button btn-lg' %>
	            </div>
	          </div>
	<% end %>


	</div>
	    <div class="bg-green-banner padding col-lg-12">
    	<h2>Don't want to show this piece on Artbnb anymore?</h2>
    	<br />
    	<h6>Click below to remove your artwork for the Artbnb gallery!</h6>
    	<br />
      	<p class="btn green-button btn-lg"><%= link_to "delete my art", artwork_path(@artwork), method: :delete, data: {confirm: "Are you sure?"} %></p>
<br />
<br />
    </div>
  </div>
</div>

app/views/artworks/index.html.erb
<p><center><h1 class="green-text">All artwork</center></h1></p>
<hr />
  <%#= render 'users/search' %>
<!-- <hr /> -->
<p>
<ul>
<% @artworks.in_groups_of(3, false).each do |group| %>
  <div class='row'>
  	<center>
    <%# group.each do |artwork| %>
    <% group.sort { |a,b| b.likes(group).count <=> a.likes(group).count }.each do |artwork| %>
    <li>
      <div class='col-lg-4 col-md-4 col-sm-4'>
        <div class='col-lg-1 col-md-1 col-sm-1'>
        </div>
        <div class='col-lg-10 col-md-10 col-sm-10 border'>
        <%= link_to image_tag(artwork.image.url(:medium)), artwork_path(artwork) %>
        <div>
          <h3><%= artwork.title %></h3>
          <h4><%= artwork.user.name %> | <%= artwork.user.city %></h4>
  		    <p>Likes: <%= artwork.likes.count %>
  				  <% artwork.likes.each do |like| %>
  				    <%= image_tag like.user.profile.url, width: 20, height: 20 %>
  			   <% end %>
  		    </p>
          <h3><%= number_to_currency(artwork.price) %></h3>
        </div>
        <p class="btn green-button btn-lg"><%= link_to "Buy this piece!", artwork_path(artwork) %></p>
        </div>
        <div class='col-lg-1 col-md-1 col-sm-1'>
        </div>
      </div> 
      </li>
    <% end %>

      
	  </center>
<br />
  </div>
<br />
<% end %>
<div align="center">
      <%= will_paginate %>
    </div>
</ul>
</p>
<hr />
<div class="row" align="center">
<p>
  <% if user_signed_in? && current_user.artist? %> 
    <%= link_to "Upload your art!", new_artwork_path %>
    <hr />
  <% else %>
    <% %>
  <% end %>
</p>
</div>

app/views/artworks/new.html.erb
<div class="container">

  <div class="row" align="center">
    <div class="bg-upload-your-art col-lg-12 ">

		<h1 class="green-text">Upload your artwork!</h1>

		<%= render 'artworkform' %>



	</div>
	    <div class="bg-green-banner padding col-lg-12">
    	<h2>Want to get paid? Connect with Stripe!</h2>
    	<br />
    	<h6>Click below to create a free Stripe account in a few minutes. Then begin processing payments immediately!</h6>
    	<br />
      <a href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_9KPeIErNZ8gTC4NkQsdQcyzVT7yQhkI1&scope=read_write" class="stripe-connect dark"><span>Connect with Stripe</span></a>
<br />
<br />
    </div>
  </div>
</div>

app/views/artworks/show.html.erb
<div class="container">

  <div class="row">
    <br />
    <div class="col-lg-12">
      <div class="col-lg-3 left">
        <p>
          <br /><br /><br /><br /><br /><br /><br /><br /><br />
          <h2 class="green-text"> 
            <%= @artwork.title %>
            <br />
          </h2>
          <h3>
            Price: <%= number_to_currency(@artwork.price) %> 
          </h3>
        </p>
        <p>Description: <%= @artwork.description %> </p>
        <p>
          <div id="artwork_<%= @artwork.id %>_likes">
            <%= render partial: "likes", locals: {artwork: @artwork} %>
          </div>
        </p>
      </div>
      <div class="col-lg-6 center">
        <p> <%= image_tag @artwork.image.url(:large), width: 600, height: 600 %> </p>
      </div> 
      <div class="col-lg-3 right">
        <p> 
          <br /><br /><br /><br /><br /><br />
          <%= image_tag @artwork.user.profile.url(:thumb), class: "img-circle" %> 
          <h2><%= link_to @artwork.user.name, user_path(@artwork.user) %></h2>
          <h5><%= @artwork.user.role %></h5>
          <h5><%= @artwork.user.city %>, <%= @artwork.user.country %></h5>
          <%= link_to "Message this artist!", new_conversation_path(@user) %>
        </p>
      </div>
    </div>

    <div class="col-lg-12 center">
      <%= render 'payment' %>
      <hr />
    </div>


    <div class="col-lg-12 center">
      <%= link_to "See More Artwork", artworks_path %>
      <hr />
    </div> 

  </div>
</div>