config/routes.rb
Rails.application.routes.draw do
  get 'news/index'

	devise_for :users

	root to: "static_pages#home"

	get "/alt" => 'static_pages#alt'

	resources :users  
	resources :artworks do 
		resource :like, module: :artworks
	end
	resources :venues
	resources :conversations do
		resources :messages

		collection do 
			get :inbox
			get :all, action: :index
			get :sent 
			get :trash 
		end
	end
	resources :friendships

	# match 'auth/:provider/callback', to: 'sessions#create'
	
	get "artworks" => 'artworks#index'
	get "venues" => 'venues#index'

	get "my_friends", to: 'users#my_friends'
	get 'search_friends', to: "users#search"
	post 'add_friend', to: "users#add_friend" 

	get "thanks", to: "users#thanks"
	get "stripe", to: "users#stripe"

	get "news", to: 'news#index'

end

app/models/user.rb
class User < ApplicationRecord
	has_many :artworks 
	has_many :venues 

	has_many :friendships
	has_many :friends, :through => :friendships

    has_many :conversations
    has_many :notifications, foreign_key: :recipient_id

	enum role: [:admin, :artist, :venue_owner, :collector, :private_dealer, :educator, :art_student, :media]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role 
		self.role ||= :artist
	end

	has_and_belongs_to_many :roles

  	devise :database_authenticatable, :registerable, 
           :recoverable, :rememberable, :trackable, :validatable

    acts_as_messageable 

	def mailboxer_email(object)
		self.email
	end

	has_attached_file :profile, styles: { thumb: "150x150#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :profile, content_type: /\Aimage\/.*\z/
	# validates_attachment_content_type :profile, :content_type => ["jpg", "jpeg", "png", "gif"]

	has_many :likes
    has_many :liked_artworks, :through => :likes, :source => :artwork

	def likes?(artwork)
		artwork.likes.where(user_id: id).any?
	end

  	def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  	end

    def not_friends_with?(friend_id)
    	friendships.where(friend_id: friend_id).count < 1 
    end

    def except_current_user(users)
    	users.reject { |user| user.id == self.id }
    end

    def self.search(param)
    	return User.none if param.blank?

    	# param.strip!
    	(city_matches(param) + country_matches(param)).uniq
    end

    def self.name_matches(param)
    	matches('name', param)
    end

    def self.email_matches(param)
    	matches('email', param)
    end

    def self.city_matches(param)
        matches('city', param)
    end

    def self.country_matches(param)
        matches('country', param)
    end

    def self.matches(field_name, param)
    	where("lower(#{field_name}) like ?", "%#{param}%")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :index
	after_action :verify_authorized

	def show 
		@user = User.find(params[:id])
		authorize User
	end

  	def index
    	@users = User.paginate(page: params[:page], per_page: 20)
    	authorize User
  	end

    def update
        @user = User.find(params[:id])
        redirect_to thanks_path
        authorize User
    end

    def thanks
        @user = current_user
        authorize User
    end

    def stripe
        @user = current_user
        authorize User
    end

    def my_friends
        @friendships = current_user.friends
        authorize User
    end

	def search
        @users = User.search(params[:search_param])

        if @users
            @users = current_user.except_current_user(@users)
            render partial: 'friends/lookup'
        else
            render status: :not_found, nothing: true
        end
        authorize User
    end

    def add_friend
        @friend = User.find(params[:friend])
            current_user.friendships.build(friend_id: @friend.id)
                if current_user.save
                    redirect_to my_friends_path, notice: "Friend was successfully added."
                else
                    redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend."
                end
        authorize User
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_artists.html.erb
<p> <%= image_tag @user.profile.url(:thumb) %> <% @user.each do |user| %>
  <li><%= image_tag user.profile.url(:thumb) %> <br/> <%= link_to user.title, users(artist) %></li><br />
  <% end %> </p>

app/views/users/_artworks.html.erb
<div class='col-lg-12 center padding green-text'>
  <% if @user == current_user %>
  <p><h2 align="center"> Your gallery:</h2></p>
<% else %>
  <p><h2 align="center"> <%= @user.name %>'s gallery:</h2></p>
<% end %>
</div>
<div class='col-lg-12'>
  <% if @user.artworks.size > 0 %>
<ul>
<% @user.artworks.in_groups_of(3, false).each do |group| %>
  <div class='row'>
  	<center>
    <% group.each do |artwork| %>
    <li>
      <div class='col-lg-4 col-md-4 col-sm-4'>
        <%= link_to image_tag(artwork.image.url(:medium)), artwork_path(artwork) %>
        <h4><%= artwork.title %></h4>
		    <h6>Likes: <%= artwork.likes.count %>
				<% artwork.likes.each do |like| %>
				    <%= image_tag like.user.profile.url, width: 20 %>
			   	<% end %>
		    </h6>
        <% if @user == current_user %>
          <% %>
        <% else %>
          <p class="btn green-button btn-lg"><%= link_to "Buy this piece!", artwork_path(artwork) %></p>
        <% end %>
        <br />
      </div>
      </li>
    <% end %>

	</center>	
  </div>
<% end %>
<br />
<% else %>
<div class= "row col-lg-12 center">
  <% if @user == current_user %>
    <p class= "lead">You haven't uploaded any artwork yet!</p>
  <% else %>
    <p class= "lead"><%= @user.name %> hasn't uploaded any artwork yet!</p>
  <% end %>
</div>
<% end %>
</ul>
  <div class="center">
    <% if current_user.artist? && @user == current_user %> 
      <%= link_to "Upload your artwork!", new_artwork_path %>
    <% end %>
  </div>
<hr />
</div>

app/views/users/_likes.html.erb
<div class='col-lg-12 center padding green-text'>
  <% if @user == current_user %>
  <p class="green-text"><h2 align="center"> Your favorite pieces of art: </h2></p>
<% else %>
  <p><h2 align="green-text center"> <%= @user.name %>'s favorite pieces of art:</h2></p>
<% end %>

</div>
<div class='col-lg-12 center '>
  <div class='col-lg-12 center padding'>
<% if @user.likes.size > 0 %>
<ul>
<% @user.likes.in_groups_of(6, false).each do |group| %>
  <div class='row col-lg-12'>
    <center>
    <% group.each do |like| %>
    <li>
      <div class='col-md-2 padding'>
        <p>
          <%= link_to image_tag(like.artwork.image.url(:medium), width: 200), artwork_path(like.artwork) %>
          <h4><%= like.artwork.title %></h4>
          <h5><%= like.artwork.user.name %> | <%= like.artwork.user.city %></h5>
          <h4><%#= number_to_currency(like.artwork.price) %></h4>
        </p>
      </div>
      </li>
    <% end %>
    <br />
  </center> 

  </div>
<% end %>
</ul>
</div>
<div>
<br />
</div>
<% else %>
<div class= "row col-lg-12 center">
  <% if @user == current_user %>
    <p class= "lead">You haven't liked any artwork yet!</p>
  <% else %>
    <p class= "lead"><%= @user.name %> hasn't liked any artwork yet!</p>
  <% end %>
</div>
<% end %>
<p><%= link_to "See More Art!", artworks_path %></p>
</div>

app/views/users/_search.html.erb
<div class="row">
	<div class="col-md-12">
	<div id="friend-lookup">
	<h3 class="center">Find An Artist Near You</h3>
		<%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
			      <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-1">
          <%   %>
        </div>
        <div class="col-md-8">
          <%= text_field_tag :search_param,
            params[:search_param],
            placeholder: 'City or Country',
            class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
            <i class='fa fa-search'></i> Search Artists
          <% end %>
        </div>
        <div class="col-md-1">
          <%   %>
        </div>
      </div>
	<% end %>
<%= render 'shared/spinner' %>
	<% if @users %>
	<% if @users.size > 0 %>
	<div class="row">
	<div class="col-md-12">
		<div class="col-md-12 center">
			<h3>Search Results</h3>
		</div>
		<div class="col-md-1">
		</div>
			<div id="friend-lookup-results" class="well results-block col-md-10">
				<table class="search-results-table col-md-12">
					<tbody>
						<% @users.each do |user| %>
							<tr>
								<td><%= image_tag user.profile.url(:thumb), width: 60 %></td>
								<td><strong>Name:</strong> <%= user.name %></td>
								<td><strong>Location:</strong> <%= user.city %>, <%= user.country %></td>
								<td><strong>Role:</strong> <%= user.role %></td>
								<td>
									<%= link_to "View Profile", user_path(user), class: "btn btn-xs green-button" %>
								</td>
								<td>
									<% if current_user.not_friends_with?(user.id) %>
									<%= link_to "Add as friend", add_friend_path(user: current_user, friend: user),
										class: 'btn btn-xs green-button', method: :post %>
									<% else %>
										<span class='label label-primary'>
											You are friends
										</span>
									<% end %>
								</td>
								<td><%= link_to "Send Message", new_conversation_path(user), class: "btn btn-xs green-button" %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="col-md-1">
			</div>
									<% else %>
										<p class="lead col-md-12 center">
											No people match this search criteria
										</p>
								<% end %>
					<% end %>
	</div>
	</div>
<div id="friend-lookup-errors"></div>
</div>
</div>
</div>

app/views/users/index.html.erb
<p><center><h1>All artists</h1></center></p>
<hr />

<p>
<ul>
<% @users.where("role = 1").in_groups_of(4, false).each do |group| %>
  <div class='row'>
  	<center>
    <% group.each do |user| %>
    <li>
      <div class='col-md-3 col-sm-3 col-xs-6'>
        <%= link_to image_tag(user.profile.url(:thumb)), user_path(user) %>
        <h3><%= user.name %></h3>
        <h5><%= user.city %>, <%= user.country %></h5>
        <div><%= link_to "Message me", new_conversation_path(user) %></div><br />
        </li>
    <% end %>
	</center>
  </div>
<% end %>
<div align="center">
  <%= will_paginate %>
</div>
</ul>
</p>
<hr />
<div class="row" align="center">
<p>
<%= link_to "Send New Message", new_conversation_path %>
</p>
<hr />
</div>
<div class="row">
  <div class="col-md-12">
  <div id="friend-lookup">
  <h3 class="center">Find An Artist Near You</h3>
    <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
      <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-1">
          <%   %>
        </div>
        <div class="col-md-8">
          <%= text_field_tag :search_param,
            params[:search_param],
            placeholder: 'City or Country',
            class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
            <i class='fa fa-search'></i> Search Artists
          <% end %>
        </div>
        <div class="col-md-1">
          <%   %>
        </div>
      </div>
  <% end %>
<%= render 'shared/spinner' %>
<!--   <% if @users %>
  <% if @users.size > 0 %>
  <div class="row">
  <div class="col-md-12">
    <div class="col-md-12 center">
      <h3>Search Results</h3>
    </div>
    <% if false %>
    <div class="col-md-1">
    </div>
      <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-table col-md-12">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.profile.url(:thumb), width: 60 %></td>
                <td><strong>Name:</strong> <%= user.name %></td>
                <td><strong>Location:</strong> <%= user.city %>, <%= user.country %></td>
                <td><strong>Role:</strong> <%= user.role %></td>
                <td>
                  <%= link_to "View Profile", user_path(user), class: "btn btn-xs green-button" %>
                </td>
                <td>
                  <% if current_user.not_friends_with?(user.id) %>
                  <%= link_to "Add as friend", add_friend_path(user: current_user, friend: user),
                    class: 'btn btn-xs green-button', method: :post %>
                  <% else %>
                    <span class='label label-primary'>
                      You are friends
                    </span>
                  <% end %>
                </td>
                <td><%= link_to "Send Message", new_conversation_path(user), class: "btn btn-xs green-button" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-1">
      </div>
                  <% else %>
                    <p class="lead col-md-12 center">
                      No people match this search criteria
                    </p>
                <% end %>
          <% end %>
          <% end %> -->
  </div>
  </div>
<div id="friend-lookup-errors"></div>
</div>
</div>
</div>
<hr />

app/views/users/my_friends.html.erb
	<div class="row">
		<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
			<% if @friendships.size > 0 %> 
				<table class="table table-striped">
					<thead>
						<tr>
							<th colspan="8" class="page-header">
								<h1><%= current_user.name %>'s Friends</h1>
								<hr />
							</th>
						</tr>
						<tr>
							<th><h2> </h2></th>
							<th><h2>Name</h2></th>
							<th><h2>Email</h2></th>
							<th><h2>Actions</h2></th>
						</tr>
					</thead>
					<tbody>
						<% @friendships.each do |friend| %>
							<tr>
								<td><%= image_tag friend.profile.url(:thumb) %></td>
								<td><h3><%= friend.name %></h3></td>
								<td><h3><%= friend.email %></h3></td>
								<td class="hidden-md hidden-sm hidden-xs">
									<%= link_to "View Profile", 
										user_path(friend), 
										class: "btn green-button btx-xs" %>
									<%= link_to 'Remove Friend',
										friendship_path(friend),
										:method => :delete,
										:data => { :confirm => 'Are you sure?' },
										:class => 'btn green-button btx-xs' %>
								</td>
								<td class="hidden-xl hidden-lg">
									<%= link_to "View Profile", 
										user_path(friend), 
										class: "btn green-button btx-xs" %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% else %> 
				<div class= "row col-lg-12">
					<p class= "lead">You don't have any friends yet. Please add some!</p>
				</div>
			<% end %>
		</div> 
	</div>
<hr />
<div class="row">
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
	<%= render 'friends/lookup' %>
	</div> 
</div>
<hr />

app/views/users/show.html.erb
<% if @user == current_user %>
	<p><h2 align="center"> Welcome to your profile page, <%= @user.name %>!</h2></p>
<% else %>
	<p><h2 align="center"> Welcome to <%= @user.name %>'s profile page!</h2></p>
<% end %>
<hr />
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<p> <%= image_tag @user.profile.url(:thumb), class: "img-circle" %> 
			<h5><%= @user.role %></h5>
			<h5><%= @user.city %>, <%= @user.country %></h5>
  		</p>
	</div>
</div>
<hr />
<div>
	<% if @user.artist? %> 
			<%= render 'artworks' %>
			<hr />
		<% end %>
</div>
	<%= render 'likes' %>
	<hr />
<hr />
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		
<!-- 		<% if current_user.venue_owner? && @user == current_user %> 
			<%= link_to "Register your venue!", new_venue_path %>
			<hr />
		<% end %> -->

		<% if @user == current_user %>
			<% %>
		<% else %>
		<hr />
			<p>Want to send <%= @user.name %> a message? </p>
			<p><%= link_to "Click here", new_conversation_path(@user) %></p>
		<% end %>
	</div>
</div>
<div>
	<hr />

app/views/users/stripe.html.erb
<div class="container">

  <div class="row" align="center">
    <div class="bg-stripe col-lg-12 ">

      <h1 class="green-text">Are you ready to start getting paid for creating art?</h1>

      <br />

      <h2>Artbnb has made it easy for artists and art patrons to send and receive payments by integrating with Stripe.</h2>

      <br />

      <h5>Stripe is the easiest way for individuals and businesses to accept payments. Our users are able to instantly process major international debit or credit cards, including Visa, MasterCard and American Express. Furthermore, our users don't need a merchant account, so they can start accepting payments today!</h5>

    </div>

    <div class="bg-green-banner padding col-lg-12">
    	<h6>Click below to create a free Stripe account in a few minutes. Then begin processing payments immediately!</h6>
    	<br />
      <a href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_9KPeIErNZ8gTC4NkQsdQcyzVT7yQhkI1&scope=read_write" class="stripe-connect dark"><span>Connect with Stripe</span></a>
<br />
<br />
    </div>

  </div>
</div>
<div>
  </div>

app/views/users/thanks.html.erb
<html>
<head>
<script type="text/javascript">
function delayedRedirect(){
    window.location = "/artworks"
}
</script>
</head>
<body onLoad="setTimeout('delayedRedirect()', 5000)">
<div class="container">

  <div class="row" align="center">
    <div class="bg-sign-in col-lg-12 ">

      <h2 class="green-text">Thank you for supporting a local artist!</h2>
      <h3 class="green-text">Now, KEEP SHOPPING!</h3>

    </div>

    <div class="bg-green-banner padding col-lg-12">
      <h4>
      	<p>You should be redirected after 5 seconds.....</p>
      	<p>Are you still here?</p>
      	<p><%= link_to "Click here to view more artwork.", artworks_path %></p>
      </h4>
    </div>

  </div>
</div>
<div>
</div>
</body>
</html>