config/routes.rb
Rails.application.routes.draw do
  get 'news/index'

	devise_for :users

	root to: "static_pages#home"

	get "/alt" => 'static_pages#alt'

	resources :users  
	resources :artworks do 
		resource :like, module: :artworks
	end
	resources :venues
	resources :conversations do
		resources :messages

		collection do 
			get :inbox
			get :all, action: :index
			get :sent 
			get :trash 
		end
	end
	resources :friendships

	# match 'auth/:provider/callback', to: 'sessions#create'
	
	get "artworks" => 'artworks#index'
	get "venues" => 'venues#index'

	get "my_friends", to: 'users#my_friends'
	get 'search_friends', to: "users#search"
	post 'add_friend', to: "users#add_friend" 

	get "thanks", to: "users#thanks"
	get "stripe", to: "users#stripe"

	get "news", to: 'news#index'

end

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <footer class="page-footer purple lighten-1">
    <!--   <div class="container-fluid"> -->
    <!--   <div class="container hidden-xs">
        <div class="row">
         <div class="col s12">
          <div class="col s6">
            <h5 class="white-text"><a href="/">Artbnb</a></h5>
            <p class="tagline">Your new home for art.</p>
          </div>
          <div class="col s6 right">
            <ul>
              <li><h5 class="white-text">Sitemap</h5></li>
              <li><a class="grey-text text-lighten-3" href="/users/sign_in">Log In</a></li>
              <li><a class="grey-text text-lighten-3" href="/users/sign_up">Register</a></li>
              <li><a class="grey-text text-lighten-3" href="/users">Connect With Artists</a></li>
              <li><a class="grey-text text-lighten-3" href="/venues">Browse Venues</a></li>
              <li><a class="grey-text text-lighten-3" href="/artworks">View Gallery</a></li>
            </ul>
          </div>
         </div>
        </div>
      </div> -->

        <div class="footer-copyright">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            		<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 white-text left">
        			    <a class="white-text" target="_blank" href="/">© 2016 ARTBNB</a>
        			  </div>
                <div class="col-lg-4 hidden-md hidden-sm hidden-xs white-text center">
                  <a class="white-text" target="_blank" href="https://www.keyportdigital.com/">KEYPORT Digital</a>
                </div>
        			  <div class="col-lg-4 col-md-6 col-sm-6 hidden-xs white-text right">
                  <a class="white-text" target="_blank" href="https://www.ironhack.com/en">Made with ♥ at Ironhack</a>
        			  </div>
              </div>
        </div>
      <!-- </div> -->
    </footer>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header logo">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <div class="artbnb-logo img-responsive img-thumbnail img-circle logo hidden-sm hidden-xs"> </div> 
    </div>
    <div class="navbar-header logo">
      <div class="navbar-brand"><%= link_to "Artbnb", root_path %></div>
      <!-- <a><%= link_to image_tag('/assets/artbnb-logo.jpg', class: 'img-responsive img-thumbnail img-circle logo', style:'height: 50px; width: 50px; margin: 4px'), root_path %> </a> -->
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right navbar">
        <!-- <li class="hidden-md hidden-sm hidden-xs"><%= link_to "Browse Venues", venues_path %></li> -->
        <li><%= link_to "View Gallery", artworks_path %></li>
        <li><%= link_to "Connect With Artists", users_path %></li>

      <li>
        <% if user_signed_in? %> 
          <%= %>
        <% else %>
          <%= link_to "Register for Artbnb", new_user_registration_path %>
        <% end %>
      </li>

      <li class="active">
        <% if user_signed_in? %> 
          <% %>
        <% else %>
          <%= link_to "Log In", new_user_session_path %>
        <% end %>
      </li>

      <% if user_signed_in? %> 
        <li class="dropdown active">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.name %> <%#= image_tag current_user.profile.url(:thumb), class: "img-circle", :size => "20x20" %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
          <%= link_to "Inbox", conversations_path %>    
          <%= link_to "View Profile", user_path(current_user) %>
          <%= link_to "My Friends", my_friends_path %>
        <% if current_user.artist? %> 
          <%= link_to "Upload Your Art", new_artwork_path %>
          <%= link_to "Connect With Stripe!", stripe_path %>
        <% end %>
        <% if current_user.venue_owner? %>
          <%#= link_to "Register Your Venue", new_venue_path %>
          <%#= link_to "Connect With Stripe!", stripe_path %>
        <% end %>
          <%= link_to "Edit Account", edit_user_registration_path(current_user) %>
          <%= link_to "Log Out", destroy_user_session_path, method: 'DELETE' %>
            </li>
        <% else %>
          <%= %>
        <% end %>            
          </ul>
        </li> 

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav> 

app/views/shared/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
	<i class="fa fa-fa-spinner fa-spin fa-2x"></i> ...
</div>